### ISSUE TITLE
"Ein Fehler ist aufgetreten"

### ISSUE THREAD

**Issue by DarkBaal** [xXSchrandXx/de.xxschrandxx.assets#2]
System Information

PHP Version:

8.2.9

WoltLab Suite Core:

6.0.2

Peak Memory Usage:

27.017/256 MiB

Request URI:

GET /assets-management/index.php?asset-add/

Referrer:

https://domain.xy/assets-management/index.php?asset-list/&trash=0

User Agent:

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36

Error

Error Message:

Call to a member function canModify() on null

Error Type:

Error

*/assets-management/lib/system/attachment/AssetAttachmentObjectType.class.php:39

Template Context:

$this->foreachVars['9b9cfc32afa311d1b90efc1b5fe7aa7af90acb60']['item'] = $this->v['child'] ?? null;
if ((is_countable($_foreach_9b9cfc32afa311d1b90efc1b5fe7aa7af90acb60) && count($_foreach_9b9cfc32afa311d1b90efc1b5fe7aa7af90acb60) > 0) || (!is_countable($_foreach_9b9cfc32afa311d1b90efc1b5fe7aa7af90acb60) && $_foreach_9b9cfc32afa311d1b90efc1b5fe7aa7af90acb60)) {
foreach ($_foreach_9b9cfc32afa311d1b90efc1b5fe7aa7af90acb60 as $this->v['child']) {
?>
====> 				<?php if ($this->v['child']->isAvailable()) { ?>
					<li<?php if ( ! $this->v['child']->checkDependencies()) { ?> style="display: none;"<?php } ?>><a<?php if ($this->v['container']->usesAnchors()) { ?> href="#<?=wcf\util\StringUtil::encodeHTML(rawurlencode($this->v['child']->getPrefixedId()));?>Container"<?php } ?>><?=$this->v['child']->getLabel();?></a></li>
				<?php } ?>
			<?php }
unset($this->v['child']);$this->v['child'] = $this->foreachVars['9b9cfc32afa311d1b90efc1b5fe7aa7af90acb60']['item'];
unset($this->foreachVars['9b9cfc32afa311d1b90efc1b5fe7aa7af90acb60']);
 } ?>
Stack Trace

#0 assets\system\attachment\AssetAttachmentObjectType->canUpload(null, 0)
*/lib/system/attachment/AttachmentHandler.class.php:256
#1 wcf\system\attachment\AttachmentHandler->canUpload()
*/lib/system/form/builder/field/wysiwyg/WysiwygAttachmentFormField.class.php:124
#2 wcf\system\form\builder\field\wysiwyg\WysiwygAttachmentFormField->isAvailable()
*/lib/system/form/builder/TFormNode.class.php:389
#3 wcf\system\form\builder\container\FormContainer->isAvailable()
*/lib/system/form/builder/TFormNode.class.php:389
#4 wcf\system\form\builder\container\FormContainer->isAvailable()
*/templates/compiled/2_wcf_1___wysiwygTabMenuFormContainer.php:56
#5 include('*/templates/compiled/2_wcf_1___wysiwygTabMenuFormContainer.php')
*/lib/system/template/TemplateEngine.class.php:340
#6 wcf\system\template\TemplateEngine->display('__wysiwygTabMenuFormContainer', 'wcf', false)
*/lib/system/template/TemplateEngine.class.php:581
#7 wcf\system\template\TemplateEngine->fetch('__wysiwygTabMenuFormContainer', 'wcf', [ container => ], true)
*/lib/system/form/builder/container/FormContainer.class.php:57
#8 wcf\system\form\builder\container\FormContainer->getHtml()
*/templates/compiled/2_wcf_1___formContainer.php:59
#9 include('*/templates/compiled/2_wcf_1___formContainer.php')
*/lib/system/template/TemplateEngine.class.php:340
#10 wcf\system\template\TemplateEngine->display('__formContainer', 'wcf', false)
*/lib/system/template/TemplateEngine.class.php:581
#11 wcf\system\template\TemplateEngine->fetch('__formContainer', 'wcf', [ container => ], true)
*/lib/system/form/builder/container/FormContainer.class.php:57
#12 wcf\system\form\builder\container\FormContainer->getHtml()
*/templates/compiled/2_wcf_1___form.php:110
#13 include('*/templates/compiled/2_wcf_1___form.php')
*/lib/system/template/TemplateEngine.class.php:340
#14 wcf\system\template\TemplateEngine->display('__form', 'wcf', false)
*/lib/system/template/TemplateEngine.class.php:581
#15 wcf\system\template\TemplateEngine->fetch('__form', 'wcf', [ form => ])
*/lib/system/form/builder/FormDocument.class.php:445
#16 wcf\system\form\builder\FormDocument->getHtml()
*/templates/compiled/2_assets_1_assetAdd.php:2486
#17 include('*/templates/compiled/2_assets_1_assetAdd.php')
*/lib/system/template/TemplateEngine.class.php:340
#18 wcf\system\template\TemplateEngine->display('assetAdd', 'assets')
*/lib/page/AbstractPage.class.php:386
#19 wcf\page\AbstractPage->show()
*/lib/page/AbstractPage.class.php:134
#20 wcf\page\AbstractPage->__run()
*/lib/system/request/Request.class.php:57
#22 wcf\http\Pipeline->process(Laminas\Diactoros\ServerRequest, wcf\http\RequestHandlerMiddleware)
*/lib/system/request/RequestHandler.class.php:147
#23 wcf\system\request\RequestHandler->handle('assets')
*/assets-management/index.php:4

**Comment by DarkBaal** [comment]
Beim Versuch einen Vermögenswert hinzuzufügen

**Comment by xXSchrandXx** [comment]
Duplikat: #1
